import type { Metadata } from 'next'
import { Montserrat, Gothic_A1 as GothicA1 } from 'next/font/google'
import './globals.css'

const monteserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-monteserrat',
})

const gothicA1 = GothicA1({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-gothic_A1',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${monteserrat.variable} ${gothicA1.variable}`}>
        {children}
      </body>
    </html>
  )
}
